[versions]

kotlin = "1.9.10"

dokka = "1.9.10"

axion-release = "1.15.5"

nyx = "0.1.1"

gradle-publish = "1.2.1"

apache-commons = "1.11.0"

guava = "32.1.3-jre"
guava-kotlin = "0.1.0"

slf4k = "0.5.2"

quilt-loom = "1.4.1"

fabric-loom = "1.5.7"

architectury = "3.4.151"
architectury-loom = "1.5.388"

github-release = "2.4.1"

modrinth-minotaur = "2.8.7"

gradleplugins = "1.6.11"

maven = "3.9.6"

fuel = "2.3.1"

[plugins]
## Kotlin Plugins
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

## Axion release plugin
### Gradle release and version management plugin.
axion-release = { id = "pl.allegro.tech.build.axion-release", version.ref = "axion-release" }

gradle-plugin-java = { id = "dev.gradleplugins.java-gradle-plugin", version.ref = "gradleplugins" }
gradle-plugin-development = { id = "dev.gradleplugins.gradle-plugin-development", version.ref = "gradleplugins" }

nyx = { id = "ca.solo-studios.nyx", version.ref = "nyx" }

gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-publish" }

[libraries]
## Kotlin stdlib
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }

kotlin-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

## Apache Commons Text
apache-commons = { group = "org.apache.commons", name = "commons-text", version.ref = "apache-commons" }

## Guava
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
guava-kotlin = { group = "ca.solo-studios", name = "guava-kotlin", version.ref = "guava-kotlin" }

# SLF4K
## SLF4K is a set of kotlin extensions for SLF4J
slf4k = { group = "ca.solo-studios", name = "slf4k", version.ref = "slf4k" }

fabric-loom = { group = "fabric-loom", name = "fabric-loom.gradle.plugin", version.ref = "fabric-loom" }

quilt-loom = { group = "org.quiltmc.loom", name = "org.quiltmc.loom.gradle.plugin", version.ref = "quilt-loom" }

architectury = { group = "architectury-plugin", name = "architectury-plugin.gradle.plugin", version.ref = "architectury" }
architectury-loom = { group = "dev.architectury.loom", name = "dev.architectury.loom.gradle.plugin", version.ref = "architectury-loom" }

github-release = { group = "com.github.breadmoirai", name = "github-release", version.ref = "github-release" }

modrinth-minotaur = { group = "com.modrinth.minotaur", name = "Minotaur", version.ref = "modrinth-minotaur" }

dokka = { group = "org.jetbrains.dokka", name = "org.jetbrains.dokka.gradle.plugin", version.ref = "dokka" }

maven-artifact = { group = "org.apache.maven", name = "maven-artifact", version.ref = "maven" }
maven-repository-metadata = { group = "org.apache.maven", name = "maven-repository-metadata", version.ref = "maven" }

fuel = { group = "com.github.kittinunf.fuel", name = "fuel", version.ref = "fuel" }

[bundles]
maven = [
    "maven-artifact",
    "maven-repository-metadata",
]
